name: Deploy

on: workflow_dispatch

jobs:
  Test-Deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.14.0]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: set -eu
      - run: mkdir ~/.ssh
      - run: echo ${{ secrets.SSH_KEY }} > ~/.ssh/key
      - run: chmod 600 ~/.ssh/key

      - run: rsync -e "ssh -i ~/.ssh/key -o StrictHostKeyChecking=no" 
             --archive --compress --delete . root@194.67.118.175:/var/www/proweber/html/
