name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs:
  build-timer:
    runs-on: ubuntu-latest
    steps:
      - name: List directories
        run: ls -lah
      - name: Go to workdir
        run: cd ./time-app
      - name: Project build
        run: docker compose up
