name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs:
  build-timer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List directories
        run: ls -lah
      - name: Go to workdir and path to app directories
        run: cd ${{ github.workspace }}/time-app && pwd && ls -lah
      - name: Project build
        run: docker compose up
