name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs:
  build-api-timer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: API package install
        run: cd ${{ github.workspace }}/time-app/api && npm i
      - name: API buildg
        run: echo "Build API"
  build-frontend-timer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Frontend package install
        run: cd ${{ github.workspace }}/time-app/frontend && npm i
      - name: Frontend build
        run: cd ${{ github.workspace }}/time-app/frontend && npm run build
      - name: List directories
        run: cd  ${{ github.workspace }}/time-app/frontend && ls -lah
  test-api-timer:
    runs-on: ubuntu-latest
    needs: build-api-timer
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: API package install
        run: cd ${{ github.workspace }}/time-app/api && npm i
      - name: API test
        run: echo "Test API"
  test-frontend-timer:
    runs-on: ubuntu-latest
    needs: build-frontend-timer
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Frontend package install
        run: cd ${{ github.workspace }}/time-app/frontend && npm i
      - name: Frontend test
        run: echo "Test frontend"
  run-api-timer:
    runs-on: ubuntu-latest
    needs: test-api-timer
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: API package install
        run: cd ${{ github.workspace }}/time-app/api && npm i
      - name: API run
        run: echo "Run API"
  run-frontend-timer:
    runs-on: ubuntu-latest
    needs: test-frontend-timer
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Frontend package install
        run: cd ${{ github.workspace }}/time-app/frontend && npm i
      - name: Frontend test
        run: echo "Run frontend"