name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs:
  build-timer:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List directories
        run: ls -lah ${{ github.workspace }}
      - name: Go to workdir
        run: cd ./time-app
      - name: Path to app directories
        run: pwd
      - name: Project build
        run: docker compose up
