name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs:
  build-timer:
    runs-on: ubuntu-latest
    steps:
      - name: Project build
        run: cd ${{ github.workspace }}/time-app && docker compose up -d
