name: My First Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: workflow_dispatch
jobs:
  Print-text:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, GitHub Actions"
