name: Greeting on variable day

on:
  workflow_dispatch:
  push:

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: DAY_OF_WEEKSS
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEKEND!"