name: Greeting on variable day

on:
  workflow_dispatch:
  push:

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is ${{ vars.DAY_OF_WEEKEND }}!"