name: Greeting on variable day

on:
  workflow_dispatch:
  push:

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
        repository: Proweber12/info-site
        path: info-site
    - run: ls -lah